function stringHash(inputString) {
    /**
     * Returns a hash code from a string
     * @param  {String} str The string to hash.
     * @return {Number}    A 32bit integer
     * @see http://werxltd.com/wp/2010/05/13/javascript-implementation-of-javas-string-hashcode-method/
     */
    function hashCode(str) {
      let hash = 0;
      for (let i = 0, len = str.length; i < len; i++) {
        let chr = str.charCodeAt(i);
        hash = (hash << 5) - hash + chr;
        hash |= 0; // Convert to 32bit integer
      }
      return hash;
    }
  
    let numberHash = hashCode(inputString); // stringHash(inputString="Desmond") => "bahdbfcfgg"
  
    const stringHash = String(numberHash)
      .split("")
      .slice(1, Infinity)
      .map((x) => x * 1)
      .map((x) => String.fromCharCode(x + 97))
      .join("");
  
    return stringHash;
  }



/*

There needs to be a name that maps from the `document.title` output to a name that the user assigns



- [QUERY - github hashing algorithm](https://www.google.com/search?client=firefox-b-1-lm&q=github+hashing+algorithm)
  - [GITHUB_SERP - hashing-algorithms](https://github.com/topics/hashing-algorithms)
    - [GITHUB_REPO - explore/CONTRIBUTING.md at main · github/explore](https://github.com/github/explore/blob/main/CONTRIBUTING.md)


[QUERY - git commit hashing algorithm](https://www.google.com/search?q=git+commit+hashing+algorithm&client=firefox-b-1-lm&sca_esv=891f019e1683b014&sxsrf=ACQVn08j9avtwyg8R8KKzmyNV4NIKPpz3A%3A1707263660421&ei=rMbCZe6oGbbh0PEPtsaEwAw&ved=0ahUKEwjurpHg9JeEAxW2MDQIHTYjAcgQ4dUDCBA&uact=5&oq=git+commit+hashing+algorithm&gs_lp=Egxnd3Mtd2l6LXNlcnAiHGdpdCBjb21taXQgaGFzaGluZyBhbGdvcml0aG0yCBAAGIAEGKIEMggQABiABBiiBDIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBEj_MFCQG1jwKXACeAGQAQCYAXCgAcUHqgEDNy4zuAEDyAEA-AEBwgIKEAAYRxjWBBiwA8ICBhAAGAcYHsICCxAAGIAEGIoFGIYDwgIHEAAYgAQYDcICCxAAGIAEGIoFGJECwgIGEAAYCBgewgIGECEYChgK4gMEGAAgQYgGAZAGCA&sclient=gws-wiz-serp)
[ARTICLE - GitLab Gitaly project now supports the SHA 256 hashing algorithm](https://about.gitlab.com/blog/2023/08/28/sha256-support-in-gitaly/)
[FEATURED_SNIPPET - ]()

Git uses hashing algorithms to generate IDs for commits and other Git objects such as blobs, trees, and tags. The bcd64dba39c90daee2e1e8d9015809b992174e34 is the ID of the commit and is a 40-character hash generated by using the SHA-1 hashing algorithm.Aug 28, 2023


https://support.google.com/websearch/answer/9351707?hl=en&visit_id=638428611418922253-1835737546&p=featured_snippets&rd=1

[ARTICLE - How’s git work? The algorithm behind](https://medium.com/geekculture/hows-git-work-the-algorithm-behind-be274f9983da)
*/